### ISSUE TITLE
Need to Spanish trained models (keras and w2v)

### ISSUE THREAD

**Issue by htaghizadeh** [fgvenegas/Twitter-Sentiment-Analysis#1]
Dear fgvenegas,

First, thanks you in advance for the interesting repository.
I need to your trained model in Spanish in order to predict some Spanish tweets.

Best regards,
Hossein

**Comment by fgvenegas** [comment]
Hi 

Thanks for the interest, but I didn't have any good results in Spanish because I don't have a big dataset to train the model. Do you have any? 

Greetings

**Comment by htaghizadeh** [comment]
Unfortunately, I don't have any access to Spanish sentiment dataset.
